- hosts: localhost
  gather_facts: no

  tasks:
    - name: make sure pm_extra_tools version
      set_fact:
        pm_extra_tools: '1.6-1.el9'
        #pm_extra_tools: '1.5-1.el9'
        #pm_extra_tools: '1.4-1.el8'
        #pm_extra_tools: '1.3-1.el8'
        #pm_extra_tools: '1.2-1.el8'
        #pm_extra_tools: '1.1-1.el8'
        #pm_extra_tools: '1.0-1.el8'
      when: pm_extra_tools is not defined
      tags: download

    - name: Download pm_extra_tools
      get_url:
        url: "https://github.com/linux-ha-japan/pm_extra_tools/releases/download/pm_extra_tools-{{ pm_extra_tools | regex_replace('^(\\d+\\.\\d+).*','\\1') }}/pm_extra_tools-{{ pm_extra_tools }}.noarch.rpm"
        dest: "./roles/pm_extra_tools-install/files/"
      tags: download

- hosts: hacluster
  become: true
  gather_facts: no
  max_fail_percentage: 0

  roles:
    - role: pm_extra_tools-install
