- hosts: hacluster
  become: true
  max_fail_percentage: 0
  gather_facts: no

  vars_prompt:
    - name: "uninstall_ok"
      prompt: |-
        Uninstall Pacemaker package.
        WARNING: all cluster configuration will be erased.
        continue ?
      private: no
      default: "y"

  roles:
    - { role: pacemaker-uninstall, when: uninstall_ok == "y" }
