- name: make sure pm_extra_tools version
  set_fact:
    pm_extra_tools: '1.6-1.el9'
  when: pm_extra_tools is not defined

- name: copy pm_extra_tools to nodes
  copy:
    src: pm_extra_tools-{{ pm_extra_tools }}.noarch.rpm
    dest: /var/tmp/
  register: rc_copy

## # yum install pm_extra_tools
#
- name: install pm_extra_tools
  yum:
    name: "{{ rc_copy.dest }}"
    disable_gpg_check: True
    state: present
